FROM locustio/locust AS builder

WORKDIR /go/src/github.com/stolostron/search-indexer
COPY ./test/ ./test/

ARG HOST="https://localhost:3010"
ARG N_CLUSTERS=2
ARG SPAWN_RATE="1.0" 

ENV N_CLUSTERS=$N_CLUSTERS
ENV HOST=$HOST
ENV SPAWN_RATE=$SPAWN_RATE

RUN echo "N_CLUSTERS=$N_CLUSTERS"
RUN echo "HOST=$HOST"
ENTRYPOINT "./test/locust.sh"