# Copyright Contributors to the Open Cluster Management project

-include /opt/build-harness/Makefile.prow

.PHONY: build
build:
	docker build -f Dockerfile . -t search-indexer

.PHONY: lint
lint:
	@echo $(shell go env)
	@echo $(shell go env GOBIN)
	go mod tidy
	$(GOBIN)/golangci-lint run
	gosec ./...

.PHONY: unit-test
unit-test:
	go test ./... -v -coverprofile cover.out
